config/routes.rb
Rails.application.routes.draw do
  resources :hashtags
  # get 'hashtags/show'
  # get 'hashtags/new'
  # get 'hashtags/edit'
  # get 'hashtags/create'
  # get 'hashtags/update'
  # get 'hashtags/delete'
  resources :post_hashtags
  # get 'post_hashtags/show'
  # get 'post_hashtags/new'
  # get 'post_hashtags/edit'
  # get 'post_hashtags/create'
  # get 'post_hashtags/update'
  # get 'post_hashtags/delete'
  resources :posts
  # get 'posts/show'
  # get 'posts/new'
  # get 'posts/edit'
  # get 'posts/create'
  # get 'posts/update'
  # get 'posts/delete'
  resources :users
  # get 'users/show'
  # get 'users/new'
  # get 'users/edit'
  # get 'users/create'
  # get 'users/update'
  # get 'users/delete'
  root 'sessions#new'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  has_many :post_hashtags
  has_many :posts, through: :post_hashtags
  validates :name, uniqueness: true

  def add_a_hashtag
    arr = self.split(' ')
    arr.map do |hsh|
      if hsh.include?('#')
        hsh
      else
        '#'+ hsh
      end
    end
    arr.join(' ')
  end
end

app/models/post.rb
 class Post < ApplicationRecord
  belongs_to :user
  has_many :post_hashtags
  has_many :hashtags, through: :post_hashtags
  validates :image, attachment_presence: true
  has_attached_file :image, styles: { medium: "640x640"}, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates :title, length: {maximum: 50}
  validates :title, :image, presence: true


  def change_to_hashtag=(string)
    hashtags = string_split(string).map do |word|

     Hashtag.find_or_create_by(name: add_a_hashtag(word))
   end
    self.hashtags = hashtags
  end

  def change_to_hashtag
    self.hashtags
    return ""
  end

  def string_split(string)
    arr = string.split(' ')
  end

  def add_a_hashtag(str)
    if str.include?('#')
      str
    else
      '#'+ str
    end
  end
end

app/models/post_hashtag.rb
class PostHashtag < ApplicationRecord
  belongs_to :post
  belongs_to :hashtag

  # def change_to_hashtag=(string)
  #   hashtag = Hashtag.find_or_create_by(name: string)
  #   hashtag = hashtag.add_a_hashtag
  #   self.body = hashtag
  # end
  # def change_to_hashtag
  #   self.body
  # end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_secure_password
  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
  validates :email, uniqueness: true
  validates :name, length: {maximum: 40}
  validates :email, length: {maximum: 75}
  validates :password, length: {maximum: 20}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_logged_in
  helper_method :current_user



  def current_user
    if session[:user_id]
      @user = User.find(session[:user_id])
    end
  end

  private
  def require_logged_in
    redirect_to controller: 'sessions', action: 'new' unless current_user
  end
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  def show
    @hashtag = Hashtag.find(params[:id])
    render :layout => 'hashtag_posts'
  end

  def new
    @hashtag = Hashtag.new
  end

  def edit
  end

  def create

  end

  def update
  end

  def delete
  end

  private

  def hashtag_params
    params.require(:hashtag).permit(:name)
  end
end

app/controllers/post_controller.rb
class PostsController < ApplicationController
  before_action :find_params, only: [:show, :edit, :destroy]
  layout 'pages'

  def index
    @posts = Post.all
    render :layout => 'all_posts'
  end

  def show
    # byebug
    render :layout => 'post'
  end

  def new
    @post = Post.new
    render :layout => 'create_post'
  end

  def edit
  end

  def create

    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.valid?
      @post.save
      redirect_to post_path(@post)
    else
      flash[:error] = @post.errors.full_messages
      redirect_to new_post_path
    end
  end

  def update
  end

  def destroy
    @post.delete
    redirect_to user_path(current_user)
  end

  private
  def find_params
    @post = Post.find(params[:id])
  end


  def post_params
    params.require(:post).permit(:title, :change_to_hashtag, :image)
  end
end

app/controllers/post_hashtags_controller.rb
class PostHashtagsController < ApplicationController
  def show
  end

  def new
  end

  def edit
  end

  def create
  end

  def update
  end

  def delete
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_logged_in, only: [:new, :create]
  # skip_before_action :current_user, only: [:new, :create]
  layout 'application'

  def new
    render :new
  end

  def create
    #byebug

    @user = User.find_by(email: params[:session][:email])

    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      redirect_to login_path
      flash[:notice] = "Incorrect username/password"
    end
  end

  def destroy
    session.delete :user_id
    current_user = nil
    redirect_to login_path
  end

  private
  def user_params
    params.permit(:email, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_params, only: [:show, :edit, :destroy, :update]
  skip_before_action :require_logged_in, only: [:new, :create]
  layout 'pages'


  def show
    render :layout => 'users'

  end

  def new
    @user = User.new
    render :layout => 'application'
  end

  def create
    @user = User.new(user_params)

    if @user.valid?
      @user.save
      redirect_to user_path(@user)
    else
      redirect_to login_path
    end
  end

  def edit
  end

  def update
    @user.update(user_params)
    #byebug
    redirect_to user_path(@user)
  end

  def destroy
    @user.delete
    reset_session
    redirect_to login_path
  end

  private
  def find_params
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
end

app/helpers/post_hashtags_helper.rb
module PostHashtagsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hashtags/new.html.erb
<h1>Hashtags#new</h1>
<p>Find me in app/views/hashtags/new.html.erb</p>

app/views/hashtags/show.html.erb
<div class="hashtag_posts">
<h1><%=@hashtag.name%></h1>
<% @hashtag.posts.reverse.each do |post|%>
  <h3> <%= link_to post.user.name.capitalize, user_path(post.user) %></h3>
  <h4 class="post-title"><%= post.title %></h4>
  <%= image_tag post.image.url(:medium), :class => "pics" %>
<% end %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-dark bg-inverse">
  <%= link_to "Login", root_path, class: "navbar-brand" %>
  <ul class="nav navbar-nav">

    <li class="nav-item active">
      <a class="nav-link" href="#">Profile <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Logout</a>
    </li>
  </ul>
  <form class="form-inline pull-xs-right">
    <input class="form-control" type="text" placeholder="Search">
    <button class="btn btn-success-outline" type="submit">Search</button>
  </form>
</nav>

app/views/layouts/all_posts.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mod2ProjectInstaclone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'all_posts', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <ul class='menu'>
        <% if current_user %>
        <li><i class="fas fa-sign-out-alt" ><%=link_to 'Logout', logout_path, method: :delete %></i></li>

        <li><i class="fas fa-user-circle" ></i><%= link_to 'Profile', user_path(current_user) %></li>

        <li><i class="far fa-edit" ><a href="/posts/new"></i>Create Post</a></li>
        <% end %>

        <li><i class="fas fa-home" ></i><a href="/posts">Home</a></li>

      </ul>

    </header>

    <body>
    <%= yield %>
  </body>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mod2ProjectInstaclone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <ul class='menu'>
        <% if current_user %>
        <li><i class="fas fa-sign-out-alt" ><%=link_to 'Logout', logout_path, method: :delete %></i></li>

        <li><i class="fas fa-user-circle" ></i><%= link_to 'Profile', user_path(current_user) %></li>

        <li><i class="far fa-edit" ><a href="/posts/new"></i>Create Post</a></li>
        <% end %>

        <li><i class="fas fa-home" ></i><a href="/posts">Home</a></li>

      </ul>

    </header>

    <body>
    <%= yield %>
  </body>

  </body>
</html>

app/views/layouts/change_password.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mod2ProjectInstaclone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'change_password', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <ul class='menu'>
        <% if current_user %>
        <li><i class="fas fa-sign-out-alt" ><%=link_to 'Logout', logout_path, method: :delete %></i></li>

        <li><i class="fas fa-user-circle" ></i><%= link_to 'Profile', user_path(current_user) %></li>

        <li><i class="far fa-edit" ><a href="/posts/new"></i>Create Post</a></li>
        <% end %>

        <li><i class="fas fa-home" ></i><a href="/posts">Home</a></li>

      </ul>

    </header>

    <body>
    <%= yield %>
  </body>

  </body>
</html>

app/views/layouts/create_post.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mod2ProjectInstaclone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'create_post', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <ul class='menu'>
        <% if current_user %>
        <li><i class="fas fa-sign-out-alt" ><%=link_to 'Logout', logout_path, method: :delete %></i></li>

        <li><i class="fas fa-user-circle" ></i><%= link_to 'Profile', user_path(current_user) %></li>

        <li><i class="far fa-edit" ><a href="/posts/new"></i>Create Post</a></li>
        <% end %>

        <li><i class="fas fa-home" ></i><a href="/posts">Home</a></li>

      </ul>

    </header>

    <body>
    <%= yield %>
  </body>

  </body>
</html>

app/views/layouts/hashtag_posts.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mod2ProjectInstaclone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'hashtag_posts', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <ul class='menu'>
        <% if current_user %>
        <li><i class="fas fa-sign-out-alt" ><%=link_to 'Logout', logout_path, method: :delete %></i></li>

        <li><i class="fas fa-user-circle" ></i><%= link_to 'Profile', user_path(current_user) %></li>

        <li><i class="far fa-edit" ><a href="/posts/new"></i>Create Post</a></li>
        <% end %>

        <li><i class="fas fa-home" ></i><a href="/posts">Home</a></li>

      </ul>

    </header>

    <body>
    <%= yield %>
  </body>

  </body>
</html>

app/views/layouts/pages.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <title>Mod2ProjectInstaclone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'pages', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <ul class='menu'>
        <% if current_user %>
          <li><i class="fas fa-sign-out-alt" id="menu-align-right"><%=link_to 'Logout', logout_path, method: :delete %></i></li>

          <li><i class="fas fa-user-circle" id="menu-align-right"></i><%= link_to 'Profile', user_path(current_user) %></li>

          <li><i class="far fa-edit" id="menu-align-right"><a href="/posts/new"></i>Create Post</a></li>
        <% end %>

        <li><i class="fas fa-home" id="menu-align-right"></i><a href="/posts">Home</a></li>

      </ul>

    </header>

    <body>
    <%= yield %>

  </body>
</html>

app/views/layouts/post.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mod2ProjectInstaclone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'post', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <ul class='menu'>
        <% if current_user %>
        <li><i class="fas fa-sign-out-alt" ><%=link_to 'Logout', logout_path, method: :delete %></i></li>

        <li><i class="fas fa-user-circle" ></i><%= link_to 'Profile', user_path(current_user) %></li>

        <li><i class="far fa-edit" ><a href="/posts/new"></i>Create Post</a></li>
        <% end %>

        <li><i class="fas fa-home" ></i><a href="/posts">Home</a></li>

      </ul>

    </header>

    <body>
    <%= yield %>
  </body>

  </body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mod2ProjectInstaclone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'users', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <ul class='menu'>
        <% if current_user %>
        <li><i class="fas fa-sign-out-alt" ><%=link_to 'Logout', logout_path, method: :delete %></i></li>

        <li><i class="fas fa-user-circle" ></i><%= link_to 'Profile', user_path(current_user) %></li>

        <li><i class="far fa-edit" ><a href="/posts/new"></i>Create Post</a></li>
        <% end %>

        <li><i class="fas fa-home" ></i><a href="/posts">Home</a></li>

      </ul>

    </header>

    <body>
    <%= yield %>
  </body>

  </body>
</html>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<div class='all-posts'>
<% @posts.reverse.each  do |post| %>
<p class="username"><%= link_to post.user.name.capitalize, user_path(post.user) %></p>
<p class='create-date'><%= post.created_at.to_time.strftime('%b %d, %Y')%></p>

<%= image_tag post.image.url(:medium), :class => 'user_post_image' %><br>
<div class='post-title'><%= post.title.capitalize %></div>
<p class="hashtags"> <% post.hashtags.each do |hashtag| %>
  <%= link_to hashtag.name, hashtag_path(hashtag) %>
  <% end %> </p>


<% end %>
</div>

app/views/posts/new.html.erb
<h1>Create a post</h1>

<% if flash[:error] %>
  <% flash[:error].each do |error| %>
    <%= error %>
  <% end %>
<% end %>

<div class="create-post-form">
<%= form_for @post do |f| %>
  <div class="form-label"><%= f.label :image %><br></div>
  <div class="file-field"><%= f.file_field :image %><br></div>
  <div class="form-label"><%= f.label 'Caption' %><br></div>
  <div class="text-field"><%= f.text_field :title %><br></div>
  <div class="form-label"><%= f.label 'Hashtag' %><br></div>
  <div class="text-field"><%= f.text_field :change_to_hashtag %><br></div>
  <div class="submit-button"><%= f.submit 'Create Post' %></div>

<% end %>
<%= link_to 'Back to profile', user_path(session[:user_id]) %>

app/views/posts/show.html.erb
  <p> <%= link_to @post.user.name.capitalize, user_path(@post.user), :class => "username" %>  </p>
  <h3 class='create-date'><%= @post.created_at.to_time.strftime('%b %d, %Y')%></h3>

  <%= image_tag @post.image.url(:medium), :class => 'user_post_image' %><br><br>
  <div class='post-caption'><%= @post.title.capitalize %></div>

  <% @post.hashtags.each do |hashtag|%>
  <%= link_to hashtag.name, hashtag_path(hashtag) %>
  <% end %><br>

  <% if session[:user_id] == @post.user.id %>
  <%= link_to 'Delete this post', @post, method: :delete %>
  <% end %>


</div>

app/views/users/edit.html.erb
<h1>Edit Profile</h1><br>
<%= form_for @user do |f| %>
<%= f.label :name %><br>
<%= f.text_field :name %><br>
<%= f.label :email %><br>
<%= f.email_field :email %><br>
<%= f.label :password %><br>
<%= f.password_field :password %><br>
<%= f.label :password_confirmation %><br>
<%= f.password_field :password_confirmation %><br>
<%= f.submit 'Edit Profile', :data => {:confirm => 'Are you sure you want to make these edits?'}%>
<% end %>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<%= link_to 'Delete my profile', @user, method: :delete, :data => {:confirm => 'Are you sure you want to delete this fabulous profile?'} %>

app/views/users/new.html.erb
<h1>Signup for Access Gram</h1><br>
<%= form_for @user do |f| %>
<%= f.label :name %><br>
<%= f.text_field :name %><br>
<%= f.label :email %><br>
<%= f.email_field :email %><br>
<%= f.label :password %><br>
<%= f.password_field :password %><br>
<%= f.label :password_confirmation %><br>
<%= f.password_field :password_confirmation %><br>
<%= f.submit 'Signup' %>
<% end %>

app/views/users/show.html.erb
<div class="user-profile">
<h1 class="username-left"><%= @user.name.capitalize %></h1>
  <% if session[:user_id] == @user.id %>
  <h3 class='edit-profile'><i class="fas fa-chess-queen"></i><%= link_to 'Edit Profile', edit_user_path(@user) %></h3>
  <% end %>

<div class="usersPics">
  <% @user.posts.reverse.each do |post| %>
  <%=link_to(image_tag(post.image.url(:medium), :class => 'user_post_image'), post_path(post)) %>
  <% end %>
</div>

</div>